/**
 * Portfolio snapshot assembly (server-side).
 *
 * Positions and cash come from persistence or the seed model; prices,
 * distributions and history always come from a MarketDataProvider. The two are
 * never mixed in the other direction — no price is ever persisted and later
 * presented as current.
 */
import type {
  Account,
  Contribution,
  CorporateAction,
  DataQuality,
  Holding,
  IncomeEvent,
  PortfolioSnapshot,
} from '../core/types.js';
import { INSTRUMENTS } from '../core/universe.js';
import { adjustDistributions, adjustPriceHistory } from '../core/corporateActions.js';
import type { MarketDataProvider } from '../market/provider.js';
import { buildSeedIncomeEvents, buildSeedModel } from '../data/seed.js';

/** Positions and cash, however they were sourced. */
export interface PositionSource {
  origin: 'database' | 'broker' | 'seed';
  accounts: Account[];
  holdings: Holding[];
  incomeEvents: IncomeEvent[] | null;
  contributions: Contribution[];
  corporateActions: CorporateAction[];
  notes: string[];
  containsMockData: boolean;
}

export const HISTORY_DAYS = 420;

/** Every symbol the dashboard may need, held or merely watched. */
export function snapshotSymbols(holdings: Holding[]): string[] {
  const symbols = new Set(INSTRUMENTS.map((i) => i.symbol));
  for (const h of holdings) symbols.add(h.symbol.toUpperCase());
  return [...symbols];
}

export function seedPositionSource(asOf: string): PositionSource {
  const seed = buildSeedModel(asOf);
  return {
    origin: 'seed',
    accounts: seed.accounts,
    holdings: seed.holdings,
    // Derived once the distribution calendar is known.
    incomeEvents: null,
    contributions: seed.contributions,
    corporateActions: seed.corporateActions,
    notes: [
      'Positions are seeded MOCK fixtures, not brokerage data.',
      'CONFIRMED holdings: 11 YMAG (Schwab) and 7.90 NVDY (Robinhood). These are the only positions permitted to drive live decisions.',
      'Every other seeded position is SIMULATED. It demonstrates the calculations but cannot activate a live strategy trigger until a brokerage adapter verifies ownership and cost basis.',
    ],
    containsMockData: true,
  };
}

export async function buildPortfolioSnapshot(args: {
  asOf: string;
  provider: MarketDataProvider;
  source: PositionSource;
  historyDays?: number;
}): Promise<PortfolioSnapshot> {
  const { asOf, provider, source } = args;
  const historyDays = args.historyDays ?? HISTORY_DAYS;
  const symbols = snapshotSymbols(source.holdings);

  const [quotes, rawHistory, rawDistributions] = await Promise.all([
    provider.getQuotes(symbols, asOf),
    provider.getPriceHistory(symbols, asOf, historyDays),
    provider.getDistributions(symbols, asOf, historyDays),
  ]);

  // Restate history across splits/reverse splits so per-share comparisons are
  // valid and a pre-split share count can never become the portfolio goal.
  const priceHistory: Record<string, typeof rawHistory[string]> = {};
  for (const [symbol, bars] of Object.entries(rawHistory)) {
    const actions = source.corporateActions.filter((a) => a.symbol.toUpperCase() === symbol.toUpperCase());
    priceHistory[symbol] = actions.length ? adjustPriceHistory(bars, actions) : bars;
  }
  const distributions = source.corporateActions.length
    ? adjustDistributions(rawDistributions, source.corporateActions)
    : rawDistributions;

  const incomeEvents = source.incomeEvents ?? buildSeedIncomeEvents(source.holdings, distributions, asOf);

  const containsMockData = source.containsMockData || provider.isMock;
  const notes = [...source.notes];
  if (provider.isMock) {
    notes.push(`Market data is generated by the "${provider.id}" mock provider. Prices and distributions are synthetic.`);
  }
  if (source.incomeEvents == null) {
    notes.push('Received-income history is derived from the mock distribution calendar.');
  }

  const dataQuality: DataQuality = containsMockData ? 'mock' : 'delayed';

  return {
    asOf,
    dataQuality,
    containsMockData,
    sourceNotes: notes,
    accounts: source.accounts,
    holdings: source.holdings,
    quotes,
    distributions,
    incomeEvents,
    contributions: source.contributions,
    priceHistory,
    corporateActions: source.corporateActions,
  };
}
